### ISSUE TITLE
Question about interface

### ISSUE THREAD

**Issue by kylegilde** [AnotherSamWilson/ParBayesianOptimization#14]
Between R versions 3.4 and 3.6, did the name of the package's function change?

I have the package installed on both versions of R, and the function seems to be called BayesianOptimization on 3.4 and bayesOpt on 3.6. The interfaces and function parameters are difference.

**Comment by AnotherSamWilson** [comment]
Yes the name of the primary function has changed from its original - I had gotten several complaints that the parameter names and functionality were unintuitive, and I agreed. Instead of drastically changing parameter names, S3 methods, and supporting features (adding iterations, saving a file, etc) I decided to create a new function and depreciate the old one in a [major release](https://github.com/AnotherSamWilson/ParBayesianOptimization/releases/tag/v1.1.0).

Sorry if this has caused any problems.

**Comment by kylegilde** [comment]
Ok, thanks for the info.
