### ISSUE TITLE
Adding categorical fields to bounds? 

### ISSUE THREAD

**Issue by waiyujack** [AnotherSamWilson/ParBayesianOptimization#16]
Thanks for creating the package and it's really useful! 

I am wondering if the package can be extended to accept categorical / logical bounds?

I can think of a few examples which would be useful in the xgboost context. 

For example, 
tree_method = approx, hist
features_selector = cyclic, shuffle, random
Or different regression family say gamma vs normal.

**Comment by AnotherSamWilson** [comment]
It is possible to do, but it is up to the user to encode the categorical variables with some idea of 'distance'. Gaussian processes, because of their construction, assume that their inputs lie on the real number line. Other packages encode each level as an integer (male = 1, female = 2, other = 3, etc.) and run the process normally. I purposely didn't implement this functionality natively because:

1. The user can do it manually, and in doing so allows for greater flexibility + forces the user to think about exactly how their categorical variables should lie on the real number line.
2. I personally never optimize over categorical variables.

There are workarounds using a specialized kernel if all inputs are categorical. This involves defining your own covariance function, like they do here: https://arxiv.org/pdf/1805.03463.pdf. You can pass your own covariance function by passing a `kernel` parameter to the dots method, which is then passed to `km()` in the `DiceKriging` package.

**Comment by rdiaz02** [comment]
A follow up question to this answer: why create a continuous parameter insteaf of an integer one, with `bounds = c(1L, 3L)`  (for three categories)?  

Using `bounds = c(0.5, 3.5)`  I think runs the risk of repeatedly exploring a parameter value that has already been explored (say, values 2.6, 2.7, ..., 3.5).  This is actually mentioned here: https://github.com/AnotherSamWilson/ParBayesianOptimization/issues/17#issuecomment-666415712
> you may waste time since the process could theoretically search the space (for example) between a=[2.5,3.5] many times, which would all return the same result.

In contrast, if we have a categorical parameter, and we code it as `bounds = c(1L, 3L)`  we can enjoy the early bailing out that is referred to in https://github.com/AnotherSamWilson/ParBayesianOptimization/issues/17
