### ISSUE TITLE
The issue caused by integers

### ISSUE THREAD

**Issue by flippercy** [AnotherSamWilson/ParBayesianOptimization#17]
Hi Mr. Wilson:

I have some thoughts on integer inputs:

As you suggested earlier, if all inputs are integers, there maybe some errors when training GP. 

Assume that part of the bound is a=c(100L, 1000L), will it be helpful if I change the search interval to a=c(100, 1000), then in the scoring function let a.rounded=round(a, 0) and use 'a.rounded' as 'a' in the function?

Appreciate your help.

**Comment by AnotherSamWilson** [comment]
This technique would keep the error from occurring - however, you may waste time since the process _could_ theoretically search the space (for example) between a=[2.5,3.5] many times, which would all return the same result. 
Theoretically this error only occurs when the most of the parameter space has been searched anyway, so if you look at scoreSummary, most (if not all) of the possible parameter sets should have been scored.

If you are finding this isn't the case, can you post a reproduceable example that shows this error occurring while leaving much of the parameter space unsearched?

**Comment by flippercy** [comment]
Hi Mr. Wilson:

Sorry for the delay. After installing the latest version of ParBayesianOptimization from github and revising my scoring function a bit (making the search space of about half of the parameters integer only), the error disappeared.

Thank you very much for your help! 

Yu
