### ISSUE TITLE
Passing training data to bayesOpt function

### ISSUE THREAD

**Issue by eduardokapp** [AnotherSamWilson/ParBayesianOptimization#25]
On the XGBoost hyperparam vignette, an example "agaricus.train" data is used. However, the `dtrain` variable is defined inside the scoring function. I don't quite understand how one would "pass" dtrain as an argument from outside the scoring function without making it a global variable. 

Am I missing something here?

**Comment by AnotherSamWilson** [comment]
This is done because dmatrix objects are pointers, and unfortunately if the process is run in parallel the pointer won't point to anything in the spun up worker. If you are not running in parallel then you can make dtrain a global variable, if you are running in parallel, you need to pass the underlying data to each worker and create the dmatrix from there.

**Comment by eduardokapp** [comment]
How would one pass the underlying data to each worker?
