### ISSUE TITLE
Package is removed from CRAN

### ISSUE THREAD

**Issue by flippercy** [AnotherSamWilson/ParBayesianOptimization#29]
Hi Mr. Wilson:

Just found out that the package has been removed from CRAN. Could you tell me why?

Thank you!

**Comment by AnotherSamWilson** [comment]
Because of the warning [here](https://cran-archive.r-project.org/web/checks/2021/2021-01-20_check_results_ParBayesianOptimization.html).

xgboost is not installed on one of the servers CRAN uses to check packages periodically. This caused the vignettes to fail to build, which caused that warning. I've fixed this issue and resubmitted, should be back up soon.
